//! Application services
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

mod example_service;

pub use example_service::ExampleService;
