//! Database seeders for the skeleton module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeders provide initial data for a fresh database. Run them via the
//! seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod example_seeder;

pub use example_seeder::SeedExampleSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Name of this seeder
    fn name(&self) -> &'static str;

    /// Execution order (lower values run earlier)
    fn order(&self) -> i32;

    /// Return true if this seeder still needs to run (for example, if its
    /// table is still empty).
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Apply the seed data.
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Optional rollback hook.
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

/// Classification of a seeder's dataset.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    Reference,
    Production,
    Development,
    Test,
}

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here.
// <<< CUSTOM SEEDERS END >>>
