//! Repository implementations
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod example_repository_impl;

pub use example_repository_impl::{ExampleRepository, TABLE_NAME as EXAMPLES_TABLE};
