//! Domain Entities
//!
//! Generated by backbone-schema. Do not edit manually.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

pub mod example;

pub use example::{Example, ExampleId, ExampleBuilder};

// =============================================================================
// Shared value objects
// =============================================================================

/// Minimal Entity trait implemented by every aggregate root in the module.
pub trait Entity {
    type Id;
    fn entity_id(&self) -> &Self::Id;
    fn entity_type() -> &'static str;
}

/// Audit metadata stored on every aggregate as a JSONB column.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AuditMetadata {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

// =============================================================================
// Enums
// =============================================================================

/// Lifecycle status for Example entities
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "example_status", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum ExampleStatus {
    Active,
    Inactive,
}

impl Default for ExampleStatus {
    fn default() -> Self {
        Self::Active
    }
}
