//! Skeleton Module
//!
//! Generated by backbone-schema. Enhanced with runtime implementations.
//!
//! This is the absolute minimum viable Backbone module, wired end-to-end
//! for one reference entity (`Example`). Rename it to your own entity and
//! regenerate with `backbone-schema schema generate`.

// Generated modules
pub mod application;
pub mod domain;
pub mod infrastructure;
pub mod presentation;
pub mod routes;
pub mod seeders;

mod module;

// Re-exports for convenience
pub use domain::entity::*;
pub use infrastructure::persistence::*;

pub use application::service::ExampleService;

pub use module::{Module, ModuleBuilder};
