//! HTTP handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide the standard Backbone CRUD endpoints.

pub mod example_handler;

pub use example_handler::create_example_routes;
